//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainShedules.ADOModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateRoute
    {
        public int DateRouteId { get; set; }
        public int RouteId { get; set; }
        public System.DateTime DateTimeBeginning { get; set; }
    
        public virtual Route Route { get; set; }
    }
}
